### ISSUE TITLE
Migration does not work with rethinkdbdash driver and port different than default

### ISSUE THREAD

**Issue by sebastian-curland** [vinicius0026/rethinkdb-migrate#10]
Hi,
When the driver used is rethinkdbdash with a port other than the default (28015), the tool does not work well and tries to run the migrations on a DB using port 28015 in the connection.
This occurs with the following config.js for example:
module.exports = {
  db: 'test',
  driver: 'rethinkdbdash',
  pool: true,
  servers: [
    {
      host: 'localhost',
      port: 48015
    }
  ]
}

The issue looks to be in function **connectToRethink**. When using rethinkdbdash with pool there is no need to do r.connect(...) since rethinkdbdash has a connection pool and manage all the connections itself.

**Comment by vinicius0026** [comment]
Hi @sebastian-curland.

You are right, there was a bug when using rethinkdbdash with pool enabled, with a port different from the default.

I created a test case with your settings, and I believe I managed to fix it. I just released a new version (1.0.1) with a patch to this bug.

Could you please try this new version and report bugs, if any?

Thanks for your time reporting this bug.

**Comment by lirantal** [comment]
Hi @vinicius0026,

Thanks for the prompt reply on this issue! 1.0.1 does indeed fixes the issue when a pool is provided with an array of servers.

When the `pool` setting is set to false while there is still a servers array the migration fails. The JSON schema validation also fails `host` and `port` instances when the rethinkdbdash driver is used. Because the rethinkdbdash driver does allow working with no connection pool (which makes sense for migrations job like this module) I would actually update the package to support it.

**Comment by sebastian-curland** [comment]
Thanks @vinicius0026 for the fix.
